### PR TITLE
Add split

### LINKED ISSUE #12: Add (split :: (Char -> Bool) -> ShortText -> [ShortText])
I missed this function when migrating some `Text`-based code to `ShortText`.

### PR DESCRIPTION
**Pull request by sjakobi**
Fixes #12.

### CODE REVIEW

**Comment by sjakobi** [comment]
Since the resulting list is always non-empty, how about we return a `(NonEmpty ShortText)` instead? `text-short` already depends on `semigroups` for GHC < 8.0, so dependencies wouldn't be a problem.

**Comment by sjakobi** [comment]
Oh, and it probably would help if I'd slap some `INLINE` pragmas on `span` and `uncons`. Would you mind?

**Comment by hvr** [comment]
@sjakobi  Thanks!  I've merged this a bit prematurely as I realise there's a few design choices to be made

I'm a bit on the fence about the NonEmpty thing as it breaks symmetry with the `intercalate` operation, which has the somewhat weird non-injective behaviour for `[""]`, i.e.

```hs
forall x . (intercalate x [] == intercalate x [""] == "")
```

Otoh, we have a choice with `split`, i.e. we can either have

- `split _ "" == []` (used by `bytestring`), or 
- `split _ "" == [""]`  (used picked by `text`)

And I'd be leaning more towards the `[]` one, as it preserves the `null` property in a homomorph-ish way; i.e.

```
null t   ===  null (split _ t)
```

otoh, the property `[""]` retains is that 

```
1+length (filter p t) === length (split p t)
```

meh... :-)

**Comment by sjakobi** [comment]
Oh boy! I didn't realize things were this complicated! ;)

I guess simply mirroring `text`'s behaviour is ok for me, but I also wouldn't mind having the other variant.

**Comment by hvr** [comment]
@sjakobi btw, the `split` implementation you provided isn't the most memory efficient one in the `ShortText` cost-model; it keeps repeatedly allocating a `rest` of the string, which is then split up again (and thus becomes garbage)

**Comment by ekmett** [comment]
I'd also generally prefer to keep the API of `text` where possible, just to minimize surprises. The `text` API is fairly opinionated and different from `bytestring` and `Data.List`, but it'd be quite surprising for a user to change a from `Text` to `TextShort` and have their code radically change meaning beyond the obvious limitations of the smaller representation.

**Pull request merged**
